// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {storage} from '../models';

export function Bootstrap():Promise<main.BootstrapData>;

export function CreateFolder(arg1:string,arg2:any,arg3:string):Promise<storage.Node>;

export function CreateProject(arg1:string):Promise<storage.Project>;

export function CreateRequest(arg1:string,arg2:any,arg3:string):Promise<main.CreateRequestResult>;

export function DeleteEnv(arg1:string):Promise<void>;

export function DeleteNode(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DuplicateRequest(arg1:string):Promise<main.CreateRequestResult>;

export function ExportOpenAPIFromDialog(arg1:string):Promise<string>;

export function ExportPostmanFromDialog(arg1:string):Promise<string>;

export function GetRequest(arg1:string):Promise<storage.Request>;

export function GetSettings():Promise<storage.Settings>;

export function GetTree(arg1:string):Promise<Array<storage.TreeNode>>;

export function ImportPostmanFromDialog():Promise<string>;

export function ListEnvs(arg1:string):Promise<Array<storage.Environment>>;

export function ListProjects():Promise<Array<storage.Project>>;

export function RenameNode(arg1:string,arg2:string):Promise<void>;

export function SaveEnv(arg1:storage.Environment):Promise<storage.Environment>;

export function SaveRequest(arg1:storage.Request):Promise<void>;

export function SaveSettings(arg1:storage.Settings):Promise<void>;

export function SendRequest(arg1:string):Promise<storage.SendResult>;

export function SetActiveEnv(arg1:string,arg2:string):Promise<void>;
