// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Bootstrap() {
  return window['go']['main']['App']['Bootstrap']();
}

export function CreateDraftRequest(arg1) {
  return window['go']['main']['App']['CreateDraftRequest'](arg1);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRequest'](arg1, arg2, arg3);
}

export function DeleteEnv(arg1) {
  return window['go']['main']['App']['DeleteEnv'](arg1);
}

export function DeleteHistory(arg1) {
  return window['go']['main']['App']['DeleteHistory'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['main']['App']['DeleteNode'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DuplicateRequest(arg1) {
  return window['go']['main']['App']['DuplicateRequest'](arg1);
}

export function ExportOpenAPIFromDialog(arg1) {
  return window['go']['main']['App']['ExportOpenAPIFromDialog'](arg1);
}

export function ExportPostmanFromDialog(arg1) {
  return window['go']['main']['App']['ExportPostmanFromDialog'](arg1);
}

export function FinalizeDraft(arg1, arg2, arg3) {
  return window['go']['main']['App']['FinalizeDraft'](arg1, arg2, arg3);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTree(arg1) {
  return window['go']['main']['App']['GetTree'](arg1);
}

export function ImportPostmanFromDialog() {
  return window['go']['main']['App']['ImportPostmanFromDialog']();
}

export function ListEnvs(arg1) {
  return window['go']['main']['App']['ListEnvs'](arg1);
}

export function ListHistory(arg1, arg2) {
  return window['go']['main']['App']['ListHistory'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function MoveNode(arg1, arg2) {
  return window['go']['main']['App']['MoveNode'](arg1, arg2);
}

export function RenameNode(arg1, arg2) {
  return window['go']['main']['App']['RenameNode'](arg1, arg2);
}

export function SaveEnv(arg1) {
  return window['go']['main']['App']['SaveEnv'](arg1);
}

export function SaveRequest(arg1) {
  return window['go']['main']['App']['SaveRequest'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetActiveEnv(arg1, arg2) {
  return window['go']['main']['App']['SetActiveEnv'](arg1, arg2);
}
